### ISSUE TITLE
Java Naming convertion

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-4#1]
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleTest_Application.java#L3
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProviderTest.java#L29
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L57
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L58
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L59
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L60
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L61
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProvider.java#L62

Обратите пожалуйста внимание на правила именования методов, классов и переменных в Java.
https://drive.google.com/file/d/1psN0db7O4GT95OxudCCx1pV9igtq2ofY/view?usp=sharing

**Comment by tanya00pm** [comment]
Поправила

**Comment by khda91** [comment]
closed
