### ISSUE TITLE
Добавить jUnit annotation

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-4#2]
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleProviderTest.java#L4

Это класс очень сильно похож на unit-test. Для того, чтобы он им стал необходимо добавить нужные аннотации из jUnit библиотеки)

**Comment by tanya00pm** [comment]
Добавлено)

**Comment by khda91** [comment]
closed
