### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-4#3]
https://github.com/tanya00pm/Homework-1_task-4/blob/d076e0111b64cf81ea2cc750c08a23e0cc3a8307/RTriangleTest_Application.java#L17

Каким образом можно ещё проверить, что треугольник является прямоугольным?

**Comment by tanya00pm** [comment]
Добавила метод getRTrianglePythagorean расчета по теореме Пифагора.
Метод вызывается в позитивном юнит-тесте (testTriangleIsRectangularPositive)

**Comment by khda91** [comment]
closed
